services:
  - type: web
    name: your-service-name
    env: python
    plan: free
    runtime: python-3.x  # Use the appropriate Python version
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 9000
